appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: XhTxs6SzeWBrgLFZSOPTtR+jKYSZWincarKNVJBgXT6kBBpF+e0SrvTksu7kGghFNaie0kVBKCyJjZHK1bokUdnxoDyjLuX5cWuqrPs1NCsWrVwDxwk3pS1dC9CA31zPgceuCIgUn6YWPvkP+IiIgo740yRvhsTh42ZPIOqR61SILL4bW1sW1iKsaAUgHGtZ+TY72m2QVE9oUOJD0iHGofU8qc/R6FN22qtjJt4wxUp7u3bluvOG/sZSCPLU+fRiYWHaKsDnI24aKgOe/WygFhgEKZiQbriBAIyzOM51B5nZc9hiAA0+7zpTRpA0uFyovyMbpaTRDMSL33RMLTikjaXT+Ajon0NsbrEhmMOertmd2+vZzGHMW4qn9QPLU9pP2BC65wAZ3yiN8PxmsKTLd2JXvI+BQCPo9zwNhdIcF4k2WcEimNaEmylkofcMdYrlMfgqVBL7mNdSs/611MHg6bXhI6Y7y76LiM8jua6w9nX824+w19u8+d95Klep3+2qgQuDTSdtm4FEBB/fEW0kod1cATsahvKCoH+AkFtkvJdz5wOOh15OspJaNO6nifSxYKvPQ/2vsgfezhPxr5Qg6bwip/OjcZAx+zYtVBb1NzMkQ8ZXwGdCeAAsPgmuk2qJJZRbQUPl5rmRbYoWPi++MjfqfUmvYwTKyXvUvxleUEc=
conda_forge_output_validation: false
